
[plantuml, "test2", png]
----
@startuml

class SendTask
{
    -IFormater* format
    -ITransfer transfer
}
skinparam classAttributeIconSize 0
IThread <|.. MeasureTask
IThread <|.. SendTask
SendTask o.. ITransfer
ITransfer <|.. Usart
SendTask o.. IFormater
IFormater <|.. Formater
SendTask o.. IFloatDataProvider
MeasureTask o.. IMeasurementsUpdate
MeasureTask o.. IMeasurementsController
IMeasurementsUpdate <|.. Temperature
IMeasurementsUpdate <|.. Humidity
IMeasurementsUpdate <|.. Preasure

IFloatDataProvider  <|.. Temperature
IFloatDataProvider  <|.. Humidity
IFloatDataProvider  <|.. Preasure
IFloatDataProvider  <|.. CalcDewPoint
ITemperature <|.. Temperature
IHumidity  <|.. Humidity
IPreasure  <|.. Preasure
IData  <|.. Temperature
IData  <|.. Humidity
IData  <|.. Preasure
IData  <|.. CalcDewPoint
BME280 o.. IData
BME280 o.. II2C
II2C <|.. I2C
IMeasurementsController <|.. BME280
CalcDewPoint o.. ITemperature
CalcDewPoint o.. IHumidity
CalcDewPoint o.. IPreasure
RegistersBME280 <|.. BME280
@enduml
----


SendTask наследует интерфейс IThread и отвечает за отправку данных. Он содержит интерфейсы IFormater для форматирования данных и ITransfer для передачи данных через USART, а также IFloatDataProvider для получения данных о температуре, влажности, давлении и точки росы.

Formater наследует интерфейс IFormater и отвечает за форматирование данных. Он использует интерфейс IFloatDataProvider для получения данных о температуре, влажности, давлении и точки росы, а также для их форматирования в строку.

Usart наследует интерфейс ITransfer и отвечает за передачу данных через USART.


MeasureTask наследует интерфейс IThread и отвечает за измерения данных. Он содержит интерфейсы IMeasurementsUpdate и IMeasurmentsController 

BME280 наследует интерфейсы IMeasurmentsController и RegistersBME280 и содержит интерфейсы II2C и IData.
I2C наследует интерфейс II2C.

Preasure наследует интерфейсы IMeasurementsUpdate, IFloatDataProvider, IData, IPreasure.

Temperature наследует интерфейсы IMeasurementsUpdate, IFloatDataProvider, IData, ITemperature.

Humidity наследует интерфейсы IMeasurementsUpdate, IFloatDataProvider, IData, IHumidity.

CalcDewPoint наследует интерфейсы IMeasurementsUpdate, IFloatDataProvider, IData.

MeasureTask получает через IMeasurmentsController сырые коды от регистров, которые отвечают за давление, температуру и влажность. Коды в свою очередь берутся из регистров, информация о которых хранится в RegistersBME280, через интерфейс II2C и класс I2C. Затем MeasureTask передаёт полученные данные через IMeasurementsUpdate в классы Humidity, Temperature и Preasure соответствующие значения регистров.
 Затем полученные данные через интерфейсы ITemperature, IHumidity и IPreasure передаются в CalcDewPoint. Так как ему для вычисления нужны только эти данные и никакие другие.
Затем когда все 4 параметра будут вычисленны они через интерфейс IFloatDataProvider передаются в SendTask, там эти данные преобразуются в строку. Эта строка затем передаётся через Usart.
IData говорит Humidity, Temperature и Preasure о том, что пора посчитаться.

Код SendTask 
----
struct variableType
{
  std::string name;
  float value;
  std::string unit;
};

void Run()
{
  std::array<variableType, dataProviderArray.size()> dataArray = {};
  for(auto it = dataProviderArray.begin(); it != dataProviderArray.end(); ++it)
  {
    auto data = it->Get();
    dataArray.push_back(data);
  }
  std::string resultString = formeter->Format(dataArray);
  transfer->Send(resultString);
}
----
