[.text-center]
= МИНИСТЕРСТВО НАУКИ И ВЫСШЕГО ОБРАЗОВАНИЯ РОССИЙСКОЙ ФЕДЕРАЦИИ
Федеральное государственное автономное образовательное учреждение высшего образования
«Южно-Уральский государственный университет» (национальный исследовательский университет) Высшая школа электроники и компьютерных наук Кафедра  «Информационно-измерительная техника»

[.text-center]
Лабораторная работа №1

[cols="30,40,30",frame=none,grid=none]
|===
| Проверил:
  Колодий
| 
| Студент:
   Серов
|===
&nbsp;

[.text-center]
Челябинск 2025

== Разработка ПО

== Структура разработки каскадного ПО
[.text-left]
* Анализ требований
разработки ПО занимает 22 процента времени работ и при этом в нём задействуется самое маленькое количество специалистов, 8 процентов. Стоимость исправления ошибки исчисляется сотнями американских долларов.
* Архитектурное проектирование программного средства
занимает так же 22 % времени и при этом задействует 14 % человеческого ресурса компании разработчика ПО. Стоимость исправления ошибки исчисляется тысячами американских долларов.
* Детальное проектирование программного средства занимает 18 % времени и 20 % человеческого ресурса. Стоимость исправления ошибки исчисляется десятками тысяч американских долларов.
* Непосредственное кодирование и тестирование программных компонентов занимает всего лишь 18% времени, но при этом 34 % человеческого ресурса компании, что говорит о том, что этот этап нередко отдаётся на откуп специализированным нейросетям. Стоимость исправления ошибки исчисляется сотнями тысяч американских долларов.
* Последний этап, а именно интеграция, квалификационное тестирование и испытания программного средства занимает 20% времени и 24 % человеческого ресурса. Стоимость исправления ошибки исчисляется миллионами американских долларов.

[.text-left]
В этой модели, её называют каскадной моделью ИТ-процессов, ошибка  возникшая на более ранних этапах жизненного цикла проекта, но своевременно не обнаруженная, может вызвать значительные задеркжи, перерасход средств и даже срыв проекта.

== Виды разработки ПО
[.text-left]

* Помимо каскадной структуры, существует и итерационный подход, он заключается в "допиливании" ПО по ходу разработки. Такой подход характерен для простейших, учебных задач. 

* Так же существует Rational Unified Process (RUP) - методология разработки программного обеспечения. В её основе лежат следующие принципы:
. Ранняя идентификация и непрерывное (до окончания проекта) устранение основных рисков.
. Концентрация на выполнении требований заказчиков к исполняемой программе (анализ и построение модели прецедентов (вариантов использования)).
. Ожидание изменений в требованиях, проектных решениях и реализации в процессе разработки.
. Компонентная архитектура, реализуемая и тестируемая на ранних стадиях проекта.
. Постоянное обеспечение качества на всех этапах разработки проекта (продукта).
. Работа над проектом в сплочённой команде, ключевая роль в которой принадлежит архитекторам.

