[plantuml, "test2", png]
----
@startuml
interface IThread
{
    {abstract} void Run()
}

class MeasureTask
{
    - mController: IMeasurementsController*
    - mUpdateT: IMeasurementsUpdate*
    - mUpdateH: IMeasurementsUpdate*
    - mUpdateP: IMeasurementsUpdate*
    - mUpdatePoint: IMeasurementsUpdate*
    + Run(): void
}

class SendTask
{
    - mFormater: IFormater*
    - mTransfer: ITransfer*
    - mDataProviders: std::vector<IFloatDataProvider*>
    + Run(): void
}

IThread <|.. MeasureTask
IThread <|.. SendTask

note bottom of IThread
  Базовый интерфейс для всех задач FreeRTOS
end note

note bottom of MeasureTask
  Задача с периодом 100 мс.
  Вызывает BME280 и обновляет все измерения
end note

note bottom of SendTask
  Задача с периодом 1 секунда.
  Форматирует и отправляет данные по USART
end note

@enduml
----