@startuml
interface ITransfer
{
    {abstract} void Send(const std::string& data)
}

class Usart
{
    + Send(const std::string& data): void
}

ITransfer <|.. Usart

note bottom of ITransfer
  Интерфейс для передачи данных
end note

note bottom of Usart
  Отправка данных через USART2.
  Скорость 9600 бод, 8 бит, 1 стоп-бит.
  Подключён к Bluetooth HC-06
end note

@enduml