@startuml
interface IMeasurementsUpdate
{
    {abstract} void UpdateCalc()
}

interface IFloatDataProvider
{
    {abstract} float GetFloatData()
}

interface IBME280Repository
{
    {abstract} int GetTemperatureData()
    {abstract} int SetTemperatureData()
    {abstract} int GetHumidityData()
    {abstract} int SetHumidityData()
    {abstract} int GetPressureData()
    {abstract} int SetPressureData()
}

note bottom of IMeasurementsUpdate
  Запускает пересчёт физической величины
end note

note bottom of IFloatDataProvider
  Предоставляет значение для форматирования строки
end note

note bottom of IBME280Repository
  Обеспечивает доступ к данным BME280
end note
@enduml