@startuml
class Pressure
{
    - repository: IBME280Repository*
    - pressureValue: float
    + UpdateCalc(): void
    + GetPressure(): float
    + GetFloatData(): float
}

interface IPressure
{
    {abstract} float GetPressure()
}

interface IBME280Repository
{
    {abstract} int GetPressureData()
    {abstract} int SetPressureData()
}

interface IMeasurementsUpdate
{
    {abstract} void UpdateCalc()
}

interface IFloatDataProvider
{
    {abstract} float GetFloatData()
}

Pressure --|> IPressure
Pressure o.. IBME280Repository
Pressure --|> IFloatDataProvider
Pressure --|> IMeasurementsUpdate

note bottom of IPressure
  Возвращает давление в гПа
end note

note bottom of IBME280Repository
  Читает и записывает сырые данные давления
end note

note bottom of IMeasurementsUpdate
  Вычисляет давление по формуле
end note

note bottom of IFloatDataProvider
  Возвращает давление для форматирования
end note
@enduml