@startuml
class Temperature
{
    - repository: IBME280Repository*
    - temperatureValue: float
    + UpdateCalc(): void
    + GetTemperature(): float
    + GetFloatData(): float
}

interface ITemperature
{
    {abstract} float GetTemperature()
}

interface IBME280Repository
{
    {abstract} int GetTemperatureData()
    {abstract} int SetTemperatureData()
}

interface IMeasurementsUpdate
{
    {abstract} void UpdateCalc()
}

interface IFloatDataProvider
{
    {abstract} float GetFloatData()
}

Temperature --|> ITemperature
Temperature o.. IBME280Repository
Temperature --|> IFloatDataProvider
Temperature --|> IMeasurementsUpdate

note bottom of ITemperature
  Возвращает температуру в °C
end note

note bottom of IBME280Repository
  Читает и записывает сырые данные температуры
end note

note bottom of IMeasurementsUpdate
  Вычисляет температуру по формуле
end note

note bottom of IFloatDataProvider
  Возвращает температуру для форматирования
end note
@enduml